### ISSUE TITLE
Failing to build the latest s6 V2.10.0.0

### ISSUE THREAD

**Issue by JSONY18** [skarnet/s6#24]
I followed the standard build process to install the latest s6.
It always getting issue on src/libs/s6_svc_ok.c, could you give me some guide how to solve the issue?
`src/libs6/s6_svc_ok.c: In function 's6_svc_ok':
src/libs6/s6_svc_ok.c:21:3: error: implicit declaration of function 'fd_islocked' [-Werror=implicit-function-declaration]
   r = fd_islocked(fd) ;
   ^
cc1: some warnings being treated as errors
make: *** [Makefile:135: src/libs6/s6_svc_ok.lo] Error 1`

**Comment by skarnet** [comment]
Just like with execline, s6-2.10.0.0 only builds with skalibs-2.10.0.0 or later. Please make sure your skalibs version is up-to-date.
